### ISSUE TITLE
Add google analytics for usage tracking

### ISSUE THREAD

**Issue by markokoskinen2037** [UniversityOfHelsinkiCS/mobvita#121]
- [x] config it so that only production server is tracked
- [x] ignore traffic from "university of helsinki"
- [x] ignore traffic from circle ci
