### ISSUE TITLE
refactor Library view to match January design

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/mobvita#135]
- [x] missing story if user has not added any
- [x] add story element
- [x] sort by
- [x] select library
- [x] more compact story cards 
https://www.figma.com/file/TfNLhL0kltOpXHvlpAllRl/MobVita-v1-(Copy)?node-id=17941%3A5774
