### ISSUE TITLE
cypress tests for flashcards

### ISSUE THREAD

**Issue by Darake** [UniversityOfHelsinkiCS/mobvita#357]
- [x] No flashcards  yet shown, when there's no flashcards
- [x] Flashcards can be added from reading mode
- [x] Flashcards can be added from practice mode
- [x] Story specific flashcards can be practiced  

- [x] Language can be changed

- [x] Translations can be seen by flipping the card

- [x] Cannot answer after checking translations
- [x] Right answer flips the card and shows thumbs up with correct translations
- [x] Wrong answer flips the cards and shows thumbs down with correct translations
- [x] Can get to the next card
