### ISSUE TITLE
add der/die/das functionality for flashcards

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/mobvita#414]
available e.g. in DE, FR, SE
- [x] article mode for all flashcards
- [x] article mode for story
- [x] menu option for float menu
- [x] menu option for big menu
