### ISSUE TITLE
add crossword mode

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/mobvita#570]
- [x] skeleton
- [x] change word focused in crossword when clicking crossword words in story text
- [x] on tab change focus to next word in crossword (in the order they are in story)
- [x] start focus with first word of the story
