### ISSUE TITLE
add leaderboards

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/mobvita#572]
- [x] Leaderboard for top n people of hours practiced. Experiment with different values.
- [x] Show users rank if not part of the top people
- [x] Change leaderboard to be for the last 1-2 weeks.
- [x] Change leaderboard to weekly_time_spent
- [x] Find a place for it. Possibly a snippet of the leaderboards in the home view which takes to full leaderboard with a click.
- [x] Add option to remove yourself from leaderboards in settings
