### ISSUE TITLE
Crosswords: style the crosswords view

### ISSUE THREAD

**Issue by Darake** [UniversityOfHelsinkiCS/mobvita#705]
- [x] adjust crosswords width based on generated crossword size
  - extra black rectangles on sides ⇒ cut away (leave no unused black rectangles)
- [x] center letters in crossword (move a little toward the bottom right: see https://www.nytimes.com/crosswords/ for examples)
- [x] _CENTERING entire view: move to the right, away from left border of screen_
- [x] _cell numbers in crossword ⇒ more visible ⇒ dark blue_
- [x] word placeholders inside story text: use "28 →" , "19 ↓" 
  - avoid "28 across", "19 down" -- (language-independence), in bluish bold font (not black bold)
- [x] correct words in crossword ⇒ green and bold in story.
  - words in story that user has filled in correctly - greenish (bold?)  (so user can find them again)
- [x] navigation: *shift tab* ⇒ go backwards (only if not difficult - now there is no way to cycle backwards?)
- [x] dont break line between number and arrow in crossword story
- [x] improve loading screen
