### ISSUE TITLE
"Encouragements" for users

### ISSUE THREAD

**Issue by ilmarikyl** [UniversityOfHelsinkiCS/mobvita#951]
# Tasks

Show "encouragement" messages to users:
- [x] STORY-COMPLETE encouragement: user completed a story in practice mode
   - got to the end past the last snippet
- [x] WELCOME-BACK encouragement: when user logs in, or comes back to open window after a while -- over 10 hours
- [x] Version 0: baseline
- [x] Version 1: more advanced
- [x] Version 2:

## Version 0:

- STORY-COMPLETE encouragement: modal messages
   - _Congratulations_
   - _You've completed X stories!_
   - _You've worked with Y words.  Would you like to review the vocabulary ?_ ⇒ Flashcards
- WELCOME-BACK encouragement: messages
   - _Welcome back!_
   - _You've completed X stories!_
   - if user is in the middle of a story:
      - _You were studying story "ABC", would you like to continue ?_  ⇒ Practice mode

All items marked XXX, YYY, ABC, etc. come from the back-end API - see below.

- Besides messages and links: show an icon from a similar-looking set -- 
   - welcome back: balloons
   - story complete: fireworks

## Version 1:

- Add one-line message to both STORY-COMPLETE and WELCOME-BACK encouragements:
   - if user's rank is in the top 100: display message:
      - _Congratulations, you are number **number X** on this week's leaderboard!!_ ⇒ with a link to LEADERBOARD View
      - _Remember: practice makes perfect!_
   - user's current rank is already available in the leaderboard API: to show current top-20 + himself
- STORY-COMPLETE encouragement: **as before*
   - _Congratulations_
   - _You've completed X stories!_
- WELCOME-BACK encouragement: **Add new message:**
   - _Welcome back!_
   - _You've completed X stories!_
   - if user is in the middle of a story:
      - _You were studying story ABC, would you like to continue ?_  ⇒ Practice mode
   - **otherwise**:
      - **_These are your recent stories: would you like to review them?_**
         - **⇒ Review mode ⇒ Last-story, Last-1, Last-2**

## Version 2:

- STORY-COMPLETE encouragement: 
   - _Congratulations_
   - _You've completed X stories!_
   - _You've worked with Y words.  Would you like to review vocabulary ?_ ⇒ Flashcards view
   - **_From this story you interacted with 103 new words. Would you like to review progress?_**
      - **⇒ Vocabulary Progress view**
- WELCOME-BACK encouragement: **as before*

# API info from BE
Currently, FE has access to at least the following information which might be interesting to the user:
* Last practiced story: story API: has special sorting key: `sorted_by_access` ⇒ info:
   - list of stories, sorted by time last accessed
* Current snippet in last practiced story: `???`
   * If current snippet in last practiced story != total snippets  ⇒ **user is in the middle of this story**
* Number of uploaded stories: `story_upload_count` in user object
* Number of covered stories: `stories_covered` in user object
* Time practiced during each week: `weekly_times`, a list in user object
* User's rank and other info regarding leaderboard: `leaderboard` in store

NB! Most (or all?) of these the info above is learning language-specific.

---
Start testing with simple modals. See example images below.

![image](https://user-images.githubusercontent.com/17416867/152938239-f39be9ae-c039-41c5-a707-aa3f52532cfb.png)

![image](https://user-images.githubusercontent.com/17416867/152938331-c05ac419-2156-4290-a77e-f82f6fb618f8.png)
